=== irinanaz/jso/XML/XML-bestanden/items.dtd
<!ELEMENT items (item*)>
<!ELEMENT item (categorie, omschrijving, prijs)>
<!ELEMENT categorie (#PCDATA)>
<!ELEMENT omschrijving (#PCDATA)>
<!ELEMENT prijs (#PCDATA)>
<!ATTLIST item id ID #REQUIRED>
<!ATTLIST prijs valuta (EUR|USD) "EUR">
<!ENTITY Cat1 "CD">
<!ENTITY Cat2 "Boek">
<!-- externe DTD : hier staat de structuur van items als het moet zijn-->

=== irinanaz/jso/XML/XML-bestanden/itemsdtd.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!--standalone="no" betekent dat er nog een externe file bij hoort-->
<!DOCTYPE items SYSTEM "items.dtd"> <!--inbouw van een externe DTD file "pad naar een file"-->
<!--Een XML bestand met CD- en boekdata -->
<items>
	<item id="id1">
		<categorie>&Cat1;</categorie><!--&Cat1; betekent de waarde van, nl. CD zie DTDfile-->
		<omschrijving>&apos;s Nachts kouder dan XML</omschrijving>
		<prijs>5.20</prijs> 
	</item>
	<item id="id2">
		<categorie>&Cat2;</categorie>
		<omschrijving>XML Family of Specifications</omschrijving>
		<prijs valuta="USD">49.99</prijs>
	</item>
	<item id="id3">
		<categorie>&Cat1;</categorie>
		<omschrijving>Ethisch XML</omschrijving>
		<prijs>3.20</prijs>
	</item>
</items>
