=== irinanaz/jso/XML/XML-bestanden/oef6b.dtd
<!ELEMENT werknemers (afdeling)* >
<!ELEMENT afdeling (arbeider*, bediende*) >
<!ATTLIST afdeling id CDATA #REQUIRED >
<!ELEMENT arbeider (naam) >
<!ATTLIST arbeider loon CDATA #REQUIRED >
<!ELEMENT bediende (naam) >
<!ATTLIST bediende loon CDATA #REQUIRED >
<!ELEMENT naam (#PCDATA) >
<!ELEMENT loon (#PCDATA) >

=== irinanaz/jso/XML/XML-bestanden/oef6b.xml
<?xml version="1.0" ?>
<!DOCTYPE werknemers SYSTEM "oef6b.dtd" >
<werknemers>
	<afdeling id="magazijn">
		<arbeider loon="2000">
			<naam>Jan</naam>
		</arbeider>
		<arbeider loon="2000">
			<naam>Piet</naam>
		</arbeider>
	</afdeling>
	<afdeling id="magazijn">
		<arbeider loon="4000">
			<naam>Corneel</naam>
		</arbeider>
		<bediende loon="4000">
			<naam>Joris</naam>
		</bediende>
	</afdeling>
</werknemers>
